services:
  - type: web
    name: chat-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn chat_app.app:app --worker-class gunicorn.workers.eventlet.EventletWorker -w 1 --bind 0.0.0.0:$PORT
    autoDeploy: true